repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.10
    hooks:
      - id: uv-lock
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .*/.*\.pgm$
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-xml
      - id: debug-statements
      - id: mixed-line-ending
      - id: fix-byte-order-marker

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args: [--max-line-length=88]
        language_version: python3.12
